trailing_return : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

trailing_return_step_0 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

trailing_return_step_1 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

trailing_return_step_2 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

trailing_return_step_3 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

trailing_return_step_4 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

bonus : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@
