basics : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@ -fdump-tree-original

template_overloading : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@

spec_simple : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@

spec_part : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@

template_order : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@

