decltype_auto : % : %.cpp
	@mkdir -p bin/
	g++ -Wall  -Wno-unused-variable -pedantic -std=c++14 $^ -o bin/$@

overload_operator : % : %.cpp
	@mkdir -p bin/
	g++ -Wall  -Wno-unused-variable -pedantic -std=c++14 $^ -o bin/$@

