class_member : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -g -Og -fno-elide-constructors -std=c++11 $< -o bin/$@

template_example : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -g -Og -fno-elide-constructors -std=c++11 $< -o bin/$@

