main : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

compare : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -Og -fno-elide-constructors -std=c++11 $^ -o bin/$@

main : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -Og -fno-elide-constructors -std=c++11 $^ -o bin/$@

