main: main.cpp
	g++ -Wall -pedantic -std=c++11 main.cpp -o main

compare: compare.cpp
	g++ -Wall -pedantic -Og -fno-elide-constructors -std=c++11 compare.cpp -o compare

order: order.cpp
	g++ -Wall -pedantic -Og -fno-elide-constructors -std=c++11 $< -o order
