decltype_entity : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@

decltype_expr : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $^ -o bin/$@
