copyable : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@

sortable : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -std=c++03 $^ -o bin/$@

