new : problem.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -Og -fno-elide-constructors -std=c++11 $^ -o bin/$@

new : problem.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -Og -fno-elide-constructors -std=c++03 $^ -o bin/$@

