simple_print_all_in_one : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

sp0 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

sp1 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

sp2 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

sp3 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

