auto_object_simple: auto_object_simple.cpp
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $< -o auto_object_simple

auto_object_classes: auto_object_classes.cpp
	g++ -Wall -Wno-unused-variable -pedantic -std=c++11 $< -o auto_object_classes
