simple_object: simple_object.cpp
	g++ -Wall -Wno-unused-variable  -g -Og -fno-elide-constructors -pedantic -std=c++11 $< -o $@

movable_object: movable_object.cpp
	g++ -Wall -Wno-unused-variable  -g -Og -fno-elide-constructors -pedantic -std=c++11 $< -o $@

