signature_template : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -g -std=c++11 $^ -o bin/$@

function_signature : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -g -std=c++11 $^ -o bin/$@

