new_auto : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_0 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_1 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_2 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_3 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_4 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_5 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

new_auto_step_6 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -Wno-unused-variable -pedantic -fno-elide-constructors -std=c++11 $^ -o bin/$@

