distance_all_in_one : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

d1 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

d2 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

d3 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

d4 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

d5 : % : %.cpp
	@mkdir -p bin/
	g++ -Wall -pedantic -g -std=c++11 $^ -o bin/$@

